# Kent's Makefile for the bfs Project

# format is the command: instructions

CFLAGS= -Wall -g

all: clean test						# Run all commands

#bfs: 								# Compile the bfs file
#	cc bfs.c -o bfs

test:								# Compile the test file
	cc test.c -o test

clean: 								# Clean the compiled files
	rm -f bfs test