# Kent's Makefile for the Hello World Project

# format is the command: instructions

CFLAGS= -Wall -g

all: clean test										# Run all commands

#helloworld: 										# Compile the hello world file
#	cc helloworld.c -o helloworld

test:												# Compile the test file
	cc test.c -o test

clean: 												# Clean the compiled files
	rm -f helloworld test