CFLAGS= -Wall -g

all: clean BFS

BFS: 
	cc BFS.c /Users/moreinibrahim/Desktop/summer2023/Code/Utilities/c-utils/src/string_builder.c -o BFS.o
#cc envokes compiler 
#BFS.c argument to compiler 
#/Users/.... argument to compiler for String Builder
# -o is the output 
#BFS.o is argument to -o (name of it)

clean:
	rm -f *.out *.o
 